### ISSUE TITLE
Test the simplest approach: Basic statistics. Can Z test be good enough to compare two distributions? Its a hypothesis testing method that evaluates whether two means are significantly different or not

### ISSUE THREAD

**Issue by juanjo255** [TheGreatJack/plodinf#2]

**Comment by TheGreatJack** [comment]
The Z-test or the t-test more likely related to the normal distribution (continous distribution). The problem here is that the distribution of allele dosage/ allele proprotion is not continuous, is discrete. And at low depths this "discretness" of the distribution is more marked. 

For this reason, the modelling of the distribution has to be made with a discrete distribution like the binomial distribution, maybe the negative binomial (that i think is used for read counts distribution in RNA-seq) or some other distribution is more appropriate. 

For now i've testing with the binomial because is simple to understand. And the way i think about this proccess is basically binomial.
